"""Initial schema with sources table

Revision ID: e805a5ba2666
Revises: 
Create Date: 2025-12-17 11:40:08.942676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e805a5ba2666'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('license_plate', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('license_plate')
    )
    op.create_table('rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dsl_content', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('camera_url', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('source_type', sa.String(), server_default=sa.text("'camera'"), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_camera_url'), 'sources', ['camera_url'], unique=True)
    op.create_index(op.f('ix_sources_file_path'), 'sources', ['file_path'], unique=False)
    op.create_index('ix_sources_is_active', 'sources', ['is_active'], unique=False)
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=False)
    op.create_index('ix_sources_source_type', 'sources', ['source_type'], unique=False)
    op.create_table('police_source_assignments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'source_id')
    )
    op.create_table('violations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('detected_license_plate', sa.String(), nullable=True),
    sa.Column('evidence_url', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_violations_detected_license_plate'), 'violations', ['detected_license_plate'], unique=False)
    op.create_index(op.f('ix_violations_rule_id'), 'violations', ['rule_id'], unique=False)
    op.create_index(op.f('ix_violations_source_id'), 'violations', ['source_id'], unique=False)
    op.create_index('ix_violations_source_timestamp', 'violations', ['source_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_violations_timestamp'), 'violations', ['timestamp'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_source_id'), 'zones', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zones_source_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_violations_timestamp'), table_name='violations')
    op.drop_index('ix_violations_source_timestamp', table_name='violations')
    op.drop_index(op.f('ix_violations_source_id'), table_name='violations')
    op.drop_index(op.f('ix_violations_rule_id'), table_name='violations')
    op.drop_index(op.f('ix_violations_detected_license_plate'), table_name='violations')
    op.drop_table('violations')
    op.drop_table('police_source_assignments')
    op.drop_index('ix_sources_source_type', table_name='sources')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_index('ix_sources_is_active', table_name='sources')
    op.drop_index(op.f('ix_sources_file_path'), table_name='sources')
    op.drop_index(op.f('ix_sources_camera_url'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('rules')
    op.drop_table('users')
    # ### end Alembic commands ###
